language: r
cache: packages
sudo: false
warnings_are_errors: false

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

#notifications
notifications:
  email:
    on_success: change
    on_failure: change

#before_script
before_script:
- R -q -e 'install.packages("http://cran.r-project.org/src/contrib/XML_3.98-1.5.tar.gz", repos = NULL)'
